package com.zaqacu.dao;

import com.zaqacu.entity.ApplyEmploy;

public interface ApplyEmployMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_employ
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    int deleteByPrimaryKey(Integer applyEmployId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_employ
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    int insert(ApplyEmploy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_employ
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    int insertSelective(ApplyEmploy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_employ
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    ApplyEmploy selectByPrimaryKey(Integer applyEmployId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_employ
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    int updateByPrimaryKeySelective(ApplyEmploy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_employ
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    int updateByPrimaryKey(ApplyEmploy record);
}