package com.zaqacu.dao;

import com.zaqacu.entity.BasicMoney;

public interface BasicMoneyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_money
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    int deleteByPrimaryKey(Integer basicMoneyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_money
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    int insert(BasicMoney record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_money
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    int insertSelective(BasicMoney record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_money
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    BasicMoney selectByPrimaryKey(Integer basicMoneyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_money
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    int updateByPrimaryKeySelective(BasicMoney record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_money
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    int updateByPrimaryKey(BasicMoney record);
}