package com.zaqacu.dao;

import com.zaqacu.entity.Check;

public interface CheckMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_tb
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    int deleteByPrimaryKey(Integer checkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_tb
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    int insert(Check record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_tb
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    int insertSelective(Check record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_tb
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    Check selectByPrimaryKey(Integer checkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_tb
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    int updateByPrimaryKeySelective(Check record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_tb
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    int updateByPrimaryKey(Check record);
}