package com.zaqacu.dao;

import com.zaqacu.entity.Employ;

public interface EmployMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employ
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    int deleteByPrimaryKey(Integer employId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employ
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    int insert(Employ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employ
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    int insertSelective(Employ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employ
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    Employ selectByPrimaryKey(Integer employId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employ
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    int updateByPrimaryKeySelective(Employ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employ
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    int updateByPrimaryKey(Employ record);
}