package com.zaqacu.dao;

import com.zaqacu.entity.MertisMoney;

public interface MertisMoneyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mertis_money
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    int deleteByPrimaryKey(Integer mertisMoneyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mertis_money
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    int insert(MertisMoney record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mertis_money
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    int insertSelective(MertisMoney record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mertis_money
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    MertisMoney selectByPrimaryKey(Integer mertisMoneyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mertis_money
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    int updateByPrimaryKeySelective(MertisMoney record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mertis_money
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    int updateByPrimaryKey(MertisMoney record);
}