package com.zaqacu.dao;

import com.zaqacu.entity.Pay;

public interface PayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    int deleteByPrimaryKey(Integer payId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    int insert(Pay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    int insertSelective(Pay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    Pay selectByPrimaryKey(Integer payId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    int updateByPrimaryKeySelective(Pay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    int updateByPrimaryKey(Pay record);
}