package com.zaqacu.dao;

import com.zaqacu.entity.TrainingType;

public interface TrainingTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_type
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    int deleteByPrimaryKey(Integer trainingTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_type
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    int insert(TrainingType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_type
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    int insertSelective(TrainingType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_type
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    TrainingType selectByPrimaryKey(Integer trainingTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_type
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    int updateByPrimaryKeySelective(TrainingType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_type
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    int updateByPrimaryKey(TrainingType record);
}