package com.zaqacu.entity;

import java.util.Date;

public class ApplyEmploy {

    private Integer applyEmployId;

    private String applyEmployName;

    private String applyEmploySex;

    private Date applyEmployBrith;

    private String applyEmployPhone;

    private String applyEmployEmail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_employ.apply_employ_id
     *
     * @return the value of apply_employ.apply_employ_id
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    public Integer getApplyEmployId() {
        return applyEmployId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_employ.apply_employ_id
     *
     * @param applyEmployId the value for apply_employ.apply_employ_id
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    public void setApplyEmployId(Integer applyEmployId) {
        this.applyEmployId = applyEmployId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_employ.apply_employ_name
     *
     * @return the value of apply_employ.apply_employ_name
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    public String getApplyEmployName() {
        return applyEmployName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_employ.apply_employ_name
     *
     * @param applyEmployName the value for apply_employ.apply_employ_name
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    public void setApplyEmployName(String applyEmployName) {
        this.applyEmployName = applyEmployName == null ? null : applyEmployName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_employ.apply_employ_sex
     *
     * @return the value of apply_employ.apply_employ_sex
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    public String getApplyEmploySex() {
        return applyEmploySex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_employ.apply_employ_sex
     *
     * @param applyEmploySex the value for apply_employ.apply_employ_sex
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    public void setApplyEmploySex(String applyEmploySex) {
        this.applyEmploySex = applyEmploySex == null ? null : applyEmploySex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_employ.apply_employ_brith
     *
     * @return the value of apply_employ.apply_employ_brith
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    public Date getApplyEmployBrith() {
        return applyEmployBrith;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_employ.apply_employ_brith
     *
     * @param applyEmployBrith the value for apply_employ.apply_employ_brith
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    public void setApplyEmployBrith(Date applyEmployBrith) {
        this.applyEmployBrith = applyEmployBrith;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_employ.apply_employ_phone
     *
     * @return the value of apply_employ.apply_employ_phone
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    public String getApplyEmployPhone() {
        return applyEmployPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_employ.apply_employ_phone
     *
     * @param applyEmployPhone the value for apply_employ.apply_employ_phone
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    public void setApplyEmployPhone(String applyEmployPhone) {
        this.applyEmployPhone = applyEmployPhone == null ? null : applyEmployPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_employ.apply_employ_email
     *
     * @return the value of apply_employ.apply_employ_email
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    public String getApplyEmployEmail() {
        return applyEmployEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_employ.apply_employ_email
     *
     * @param applyEmployEmail the value for apply_employ.apply_employ_email
     *
     * @mbggenerated Tue Aug 20 20:18:17 CST 2019
     */
    public void setApplyEmployEmail(String applyEmployEmail) {
        this.applyEmployEmail = applyEmployEmail == null ? null : applyEmployEmail.trim();
    }
}